104 auto submit after x digits entered
privacyidea/privacyidea-owncloud-app pull request #107
Opened 2023-12-05 10:43 UTC by lukasmatusiewicz

Feature:
- auto submit otp length

Refactor:
- separate the CSS from templates
- separate the JS from templates
- UI

2023-12-07 12:06 UTC, nilsbehlen requested changes

2023-12-07 12:06 UTC, nilsbehlen commented on twofactor_privacyidea/appinfo/info.xml
> +		The privacyIDEA can manage many different kind of authentication devices. Thus, you can assign different
just privacyIDEA

2023-12-07 12:06 UTC, nilsbehlen commented on twofactor_privacyidea/css/pi-form-template.css
> +.pi_images
this name uses _ while the other use camelCase. please use consistent notation

2023-12-07 12:06 UTC, nilsbehlen commented on twofactor_privacyidea/l10n/de.json
> +    "Test the authentication by supplying username and password \n            that should be checked against the privacyIDEA:" : "Sie können die Konfiguration testen, indem Sie einen Benutzernamen un
both "the" are not needed

2023-12-07 12:06 UTC, nilsbehlen commented on twofactor_privacyidea/templates/settings-admin.php
> +            <?php p($l->t('In a second step of authentication the user is asked to provide a one time password.
, after authentication

2023-12-11 08:58 UTC, lukasmatusiewicz commented on twofactor_privacyidea/appinfo/info.xml
> +		The privacyIDEA can manage many different kind of authentication devices. Thus, you can assign different
[c0c8eec](https://github.com/privacyidea/privacyidea-owncloud-app/pull/107/commits/c0c8eec64067356d0dda825987abc3ccf818fd92)

2023-12-11 09:00 UTC, lukasmatusiewicz commented on twofactor_privacyidea/l10n/de.json
> +    "Test the authentication by supplying username and password \n            that should be checked against the privacyIDEA:" : "Sie können die Konfiguration testen, indem Sie einen Benutzernamen un
[f8aa402](https://github.com/privacyidea/privacyidea-owncloud-app/pull/107/commits/f8aa40280fe1e679b6c57aa1bcf92e4bb38738af)

2023-12-11 09:48 UTC, lukasmatusiewicz commented on twofactor_privacyidea/templates/settings-admin.php
> +            <?php p($l->t('In a second step of authentication the user is asked to provide a one time password.
[5f03ff5](https://github.com/privacyidea/privacyidea-owncloud-app/pull/107/commits/5f03ff573651aa5aa04f6ffb66203a1302a0945d)

2023-12-11 09:51 UTC, nilsbehlen approved these changes

2023-12-11 09:52 UTC, merged